package com.ipn.mx.clases;
// Generated 5/01/2016 03:54:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Delegacionmunicipio generated by hbm2java
 */
@Entity
@Table(name="delegacionmunicipio"
    ,catalog="proyecto"
)
public class Delegacionmunicipio  implements java.io.Serializable {


     private Integer idDelegacionMunicipio;
     private Entidadfederativa entidadfederativa;
     private String nombreDelegacionMunicipio;

    public Delegacionmunicipio() {
    }

	
    public Delegacionmunicipio(Entidadfederativa entidadfederativa, String nombreDelegacionMunicipio) {
        this.entidadfederativa = entidadfederativa;
        this.nombreDelegacionMunicipio = nombreDelegacionMunicipio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDelegacionMunicipio", unique=true, nullable=false)
    public Integer getIdDelegacionMunicipio() {
        return this.idDelegacionMunicipio;
    }
    
    public void setIdDelegacionMunicipio(Integer idDelegacionMunicipio) {
        this.idDelegacionMunicipio = idDelegacionMunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEntidadFederativa", nullable=false)
    public Entidadfederativa getEntidadfederativa() {
        return this.entidadfederativa;
    }
    
    public void setEntidadfederativa(Entidadfederativa entidadfederativa) {
        this.entidadfederativa = entidadfederativa;
    }

    
    @Column(name="nombreDelegacionMunicipio", nullable=false, length=45)
    public String getNombreDelegacionMunicipio() {
        return this.nombreDelegacionMunicipio;
    }
    
    public void setNombreDelegacionMunicipio(String nombreDelegacionMunicipio) {
        this.nombreDelegacionMunicipio = nombreDelegacionMunicipio;
    }

}


